# Generated by Django 5.2.8 on 2025-11-19 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_trainer_alter_course_course_image_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
    ]
