# Generated by Django 5.2.8 on 2025-11-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('duration', models.DurationField()),
                ('course_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
