# Generated by Django 5.2.8 on 2025-11-19 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_alter_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='joinin_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='trainer',
            name='salary',
            field=models.FloatField(default=23),
            preserve_default=False,
        ),
    ]
