# Generated by Django 5.2.8 on 2025-11-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_trainer_joinin_date_trainer_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
