# Generated by Django 5.2.8 on 2025-12-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_alter_student_email_alter_trainer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_image',
            field=models.ImageField(default='default.png', upload_to='student/'),
        ),
    ]
